### PR TITLE
Issue411: #positive_definite?, #positive_semidefinite?, #rank_deficient?

### PR DESCRIPTION
**Pull request by johnmarinelli**
So I *think* I did what you asked (squash  all commits into one, rebase against master).  I ran git merge --squash <my-working-branch>.  Let me know if you have any questions/comments!

EDIT: nvm, it says 18 commits; how do I go about putting them all in one?

### CODE REVIEW

**Comment by v0dro** [comment]
Follow these steps to squash into one:

`git rebase -i HEAD~18`
You'll see a screen (your text editor) with commits to be squashed. Put an `s` behind each commit to be squashed.
Save that file and exit.
Type the new commit message.
You're done!

Additionally see [this page](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase/).

**Comment by v0dro** [comment]
And then you'll need to push them to your upstream with the `--force` tag.

**Comment by johnmarinelli** [comment]
@v0dro thanks man!

**Comment by mohawkjohn** [comment]
What's the status of this? Still needs rebase.

**Comment by johnmarinelli** [comment]
alright, i had two commits earlier - one was the squashed 18 commits and the next was a commit fixing merge conflicts.  for some reason I couldn't squash those two and ended up screwing stuff up. i think what would be easiest would to just fetch from upstream, copy paste my changes, and make a new pr from there.

**Pull request closed without merging**
