### PR TITLE
trsm function

### LINKED ISSUE #422: cblas_trsm behaves differently with/without lapacke plugin
When solving a lower triangular linear system with `cblas_trsm`, I get different results depending on whether I require `nmatrix-lapacke` (or `nmatrix-atlas`) or not. With the lapacke or atlas plugins I get the correct result, but without the plugins the method returns a wrong solution.

Example: The following script

```Ruby
require 'nmatrix'

a = NMatrix.new([3,3], [1, 0, 0, 2, 0.5, 0, 3, 3, 9], dtype: :float64)
b = NMatrix.new([3,1], [1,2,3], dtype: :float64)
x = b.clone
NMatrix::BLAS::cblas_trsm(:row, :left, :lower, false, :nounit, x.shape[0], 
                          x.shape[1], 1.0, a, a.shape[0], x, x.shape[1])
puts "without plugin: #{x}"

require 'nmatrix/lapacke'
a = NMatrix.new([3,3], [1, 0, 0, 2, 0.5, 0, 3, 3, 9], dtype: :float64)
b = NMatrix.new([3,1], [1,2,3], dtype: :float64)
x = b.clone
NMatrix::BLAS::cblas_trsm(:row, :left, :lower, false, :nounit, x.shape[0], 
                          x.shape[1], 1.0, a, a.shape[0], x, x.shape[1])
puts "with plugin: #{x}"
```

produces

```
without plugin: [1.0, 4.0, 0.0]
with plugin: [1.0, 0.0, 0.0]
```

The solution obtained with `nmatrix-lapacke` is the correct one (`nmatrix-atlas` gives the same correct solution).

Does anybody have an idea what might be the problem?

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #422

### CODE REVIEW

**Comment by mohawkjohn** [comment]
So made it more like the Fortran code? I suppose that's a good move. Would you please squash the commits together? Then I'll merge.

**Comment by agisga** [comment]
I think we should probably also add tests with option `:left` to the spec, because that's the problem that this commit it solving. Currently the spec only tests `cblas_trsm` with the `:right` option (see [here](https://github.com/SciRuby/nmatrix/blob/master/spec/blas_spec.rb#L55)).

**Comment by lokeshh** [comment]
Yes, it's more like the Fortran code in the sense that the loop executes in the same limits as in the Fortran code. 

I've squashed down the commits and added some tests as @agisga suggested. Are the tests good?

Earlier I created this test:

```ruby
 NMatrix::BLAS::cblas_trsm(:row, :left, :lower, :transpose, :nonunit, 1, 3, 1.0, a, 3, b, 3)
```

but it also got passed in the wrong implementation. Then I changed it to

```ruby
NMatrix::BLAS::cblas_trsm(:row, :left, :lower, :transpose, :nounit, 3, 1, 1.0, a, 3, b, 1)
```

Now only the correct implementation is passing.

**Comment by lokeshh** [comment]
I don't know why it's failing the Travis check.

**Comment by v0dro** [comment]
Stuff tends to fail at times. Investigate and restart the build if it happens again.

**Comment by v0dro** [comment]
Also, rebase into a single commit.

**Comment by lokeshh** [comment]
How can I restart the build?

**Comment by v0dro** [comment]
Google restarting travis builds.

**Pull request merged**
