### PR TITLE
fixes det method for dtype object

### PR DESCRIPTION
**Pull request by npriyadarshi**
@mohawkjohn In continuation with the work done by you in PR #501.

### CODE REVIEW

**Comment by mohawkjohn** [comment]
Seems like you're missing some code here.

**Comment by npriyadarshi** [comment]
@mohawkjohn i do not understand what part of my code is missing could you please help me out with this. Is this not the correct way to implement it?

**Comment by mohawkjohn** [comment]
Let's try this: can you please explain to me how your implementation works?

**Comment by npriyadarshi** [comment]
In the det function i type cast the object dtype to float.

**Comment by mohawkjohn** [comment]
What happens if the Object can't be cast to a decimal value? (For that matter, why would we have an `:object` dtype at all if we could always just treat it as a decimal?)

**Comment by npriyadarshi** [comment]
@mohawkjohn in lib/nmatrix/math.rb in the method det .getrf is being used on a copy(with typecasted dtype) of the matrix whose determinant is to be found out. should i throw an exception if it cannot be cast into decimal value? or is there any other way to fix the issue?

**Comment by npriyadarshi** [comment]
should i change the det function so that it does not require LAPACK function and the i can follow as in PR #514 ?

**Comment by mohawkjohn** [comment]
@npriyadarshi Let's rewind a bit. Why do we have an `:object` dtype? How does it differ from the float and integer dtypes?

**Comment by npriyadarshi** [comment]
Object dtypes represent ruby objects i mean any variable in ruby be it string,decimal, integer etc. I dont actually understand why we have dtype object.

**Comment by mohawkjohn** [comment]
We have object dtypes because matrix operations like determinants exist not only for the set of nxn integer matrices and the set of nxn real matrices, but others as well. We cannot possibly create a dtype for each of these cases because we can't envision them all. So the Ruby object dtype allows people to use those algorithms on any arbitrary domain.

**Comment by mohawkjohn** [comment]
I'm going to close this for now. You're welcome to discuss on the Google Group, or reopen when you think you've got a solution ready.

**Pull request closed without merging**
