### PR TITLE
#cov and correction for #round

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by mohawkjohn** [comment]
Hey @v0dro, I've been trying to merge this by hand, but I messed up my system and can't actually compile NMatrix right now. Would you mind rebasing this against the most recent master so I can rely on Travis and do an automatic merge?

**Comment by v0dro** [comment]
ok

**Comment by v0dro** [comment]
Hold on something got screwd

**Comment by v0dro** [comment]
@mohawkjohn I've rebased this appropriately please check it out.

Also, could you check out #297 as well?

**Pull request merged**
