### PR TITLE
Update history, manifest. Clean up CONTRIBUTING guides.

### PR DESCRIPTION
**Pull request by v0dro**

### CODE REVIEW

**Comment by v0dro** [comment]
@mohawkjohn #434

**Comment by mohawkjohn** [comment]
Merged manually with edits: https://github.com/SciRuby/nmatrix/commit/5cf682c48676e7c827d4c9952a88b7dafa6bf62b

**Comment by mohawkjohn** [comment]
By the way, @v0dro, have a look at some of the things I changed. History should present things not in terms of the issues (anyone can look at the tracker) but in terms of how this affects users. Also, make extra sure to proofread. =) You did a good job overall, I'm just really persnickety about History and Readme and such.

**Comment by v0dro** [comment]
Sure! Will do :)

**Pull request closed without merging**
