### PR TITLE
incorporates changes in #cblas_trsm (PR #428) into #solve

### PR DESCRIPTION
**Pull request by agisga**

### CODE REVIEW

**Comment by v0dro** [comment]
Why are errors showing up for Ruby 2.1.8?

And on a side note I think we should simplify the build script a little.

**Comment by mohawkjohn** [comment]
Error installing the json gem. Weird.

**Comment by agisga** [comment]
Should I reopen the pull request in order to restart the travis build, or not (because all pull requests for the last 15 days seem to be failing)?

**Comment by v0dro** [comment]
Don't reopen. 

This looks like a Travis Ruby issue because it's passing on my machine for all versions. I'm merging.

**Pull request merged**
