### PR TITLE
Improve Travis CI configuration

### LINKED ISSUE #392: Use travis-ci to test nmatrix on OS X?
Apparently travis-ci has a beta feature for testing on OS X: http://docs.travis-ci.com/user/multi-os/

I thought this might worth considering.

### PR DESCRIPTION
**Pull request by mrkn**
I'd like to improve the configuration of Travis CI in this pull request.

The following changes are made:
- Adding 2.3.0 and ruby-head
- Adding ruby versions built with clang
- Adding OSX configuration
- Use rbenv for 2.3.0 and ruby-head on OSX
- Dump some environment variables before starting script
- Use exclusion for unavailable configurations instead of commented them out
- Specify allow_failures for unstable configurations

They makes it more easy to track nmatrix stability on both linux and osx.

Currently configurations for ruby-2.3.0 and ruby-head on OSX are failed.
But I will fix them asap.

I think this PR resolves #392 and #399.

### CODE REVIEW

**Comment by v0dro** [comment]
I have fixed the ruby 2.3 error here: #432 

Do have a look.

**Comment by mohawkjohn** [comment]
Wow. I didn't know we could do this many builds without paying Travis money. I'll merge once you are able to correct a few of these. Thanks so much for working on this!

**Comment by mrkn** [comment]
#433 conflicts this PR in .travis.yml.
So I'll need to fix it after you merge #433.

**Comment by mohawkjohn** [comment]
#433 is merged. Go for it!

**Comment by v0dro** [comment]
@mohawkjohn can we have new minor version of nmatrix released after this is merged? I'd like to release a new daru version and want everything to work on ruby 2.3.

**Comment by mohawkjohn** [comment]
I think that'd be a great idea.

**Comment by mrkn** [comment]
@mohawkjohn I've rebased this onto the latest master branch.
Please merge it after passing CI.

**Comment by mrkn** [comment]
We can see one example was failed on 2.3.0: https://travis-ci.org/mrkn/nmatrix/jobs/101160262#L8013-L8023

```
Failures:
  1) math elementwise math functions yale Floor and ceil for yale complex128 should properly calculate floor for complex128
     Failure/Error: @m    = NMatrix.seq(@size, dtype: dtype, stype: stype)+1
     TypeError:
       not sure how to convert this type of VALUE to a complex
     # ./lib/nmatrix/nmatrix.rb:243:in `cast_full'
     # ./lib/nmatrix/nmatrix.rb:243:in `cast'
     # ./lib/nmatrix/math.rb:908:in `block (2 levels) in <class:NMatrix>'
     # ./spec/math_spec.rb:131:in `+'
     # ./spec/math_spec.rb:131:in `block (9 levels) in <top (required)>'
```

We should tackle to this failure on the other branch.

**Comment by mrkn** [comment]
I made a new change that moves ruby trunk on osx in allow_failures because trunk is unstable to build itself.

**Comment by mrkn** [comment]
Hmm.  Travis environment seems changed and so extconf.rb was failed.
I'm trying investigation of that.

**Comment by mrkn** [comment]
@mohawkjohn I've fixed some problems at last.
Please merge it.

**Comment by mohawkjohn** [comment]
Okay. I can merge as soon as you rebase. Thanks again, @mrkn.

**Comment by mrkn** [comment]
@mohawkjohn These commits are separated meaningfully, so it shouldn't be squashed into a single commit, I think.
For example, 3f673b0 only includes the changes about OSX configuration on travis, 50bc187 only includes the change to use CXXFLAGS, and so on.

But I can squash them if you strongly hope so.

How do you think about that?

**Pull request merged**
