### PR TITLE
fixed pretty print format for matrices

### PR DESCRIPTION
**Pull request by Aelphy**

### CODE REVIEW

**Comment by mohawkjohn** [comment]
Can you provide a little more information about what you fixed? Was there a bug report associated with this PR?

**Comment by Aelphy** [comment]
I am working on the problem of matrix read/write ruby interface. I have faced the problem, that matrix is printed via pry not like a normal matrix row under the row, but row right of the row. 

I have found it very inconvenient. Moreover I have found there a TODO: to make pretty_print method really pretty. I have deleted one extra if - because self.dim > 2 is always false in that branch of conditions.

There were no any bug report associated.

**Comment by mohawkjohn** [comment]
This is a tough one to evaluate. Usually we require a spec or something like that, but this issue seems more subjective. Can you provide some specific use-cases (examples) that have been improved?

**Comment by v0dro** [comment]
You can also provide terminal output in the comments.

**Comment by Aelphy** [comment]
what was before:

pry -r './lib/nmatrix.rb'
[1] pry(main)> g = N[[2, 3, 4], [7, 8, 9], [1,2 , 3]]
=> 
[
  [2, 3, 4]   [7, 8, 9]   [1, 2, 3] ]

What I propose:

pry -r './lib/nmatrix.rb'
[1] pry(main)> g = N[[2, 3, 4], [7, 8, 9], [1,2 , 3]]
=> 
[
  [2, 3, 4]
  [7, 8, 9]
  [1, 2, 3]
]

**Comment by v0dro** [comment]
looks good! how would this scale to dimensions greater than 2?

**Comment by Aelphy** [comment]
For the moment it fixes only the cases with 2d. I could think about greater dims.

**Comment by v0dro** [comment]
You can try to imitate octave/matlab.

**Comment by mohawkjohn** [comment]
Yeah, please check that it doesn't mess up the handling of greater dimensions. That's an area I struggled with when writing the pretty_print code originally.

**Comment by Aelphy** [comment]
I am very sorry for late reply. I have checked the code for dims grater than 3. And than analyzed conditions in branches of this method. I am sure, that my code only affects dim 2!

**Comment by Aelphy** [comment]
if self.shape.size > 1 and self.shape[1] > 100
...
elsif self.dim > 3 || self.dim == 1
...
else # it could be 0 , 2 and 3 here
  if self.dim == 3
  ...
  else # dim 2 and 0 also
  ...
  end
end

**Comment by mohawkjohn** [comment]
Be careful that this change doesn't break dimensions > 2. I believe that's why we had it doing

```
[
[2, 3, 4] [7, 8, 9] [1, 2, 3] ]
```

**Pull request merged**
