### PR TITLE
JRuby port of NMatrix.

### PR DESCRIPTION
**Pull request by prasunanand**
I haven't made any changes to gemspec and rakefile.
Also, nmatrix.gemspec could be easily modified to create a gem that can be installed on JRuby.

### CODE REVIEW

**Comment by mohawkjohn** [comment]
@prasunanand Just wanted to make sure you'd seen this.

**Comment by prasunanand** [comment]
@mohawkjohn I rebased against master.
How do I fix the travis-ci check ?

**Comment by mohawkjohn** [comment]
@prasunanand I'm trying to follow your instructions for compiling the JRuby version right now, and there is no jar task in the Rakefile. I also don't see how `bundle exec rake compile` has been adapted to allow for JRuby, but maybe I'm missing something, or your README instructions are wrong.

Note that I re-rebased your changes onto master and squashed what looked like a few extra commits (commits with the same messages). Here's the version with which I am working:

https://github.com/mohawkjohn/nmatrix/tree/jruby_master

**Comment by prasunanand** [comment]
@mohawkjohn I was referring to https://github.com/mohawkjohn/nmatrix/blob/jruby_master/ext/nmatrix_java/Rakefile for rake compile.
I am sorry for being not clear. 

I am new to travis_ci. So, didn't check about JRuby testing.

**Comment by mohawkjohn** [comment]
Okay. I think we need to merge the two Rakefiles before we can expect users to use NMatrix-JRuby.

**Comment by prasunanand** [comment]
Yeah, that can be done :smile:

**Comment by mohawkjohn** [comment]
Mind using the version I created (see link)? Saves me from having to redo
my changes again.

**Comment by prasunanand** [comment]
yeah.

**Comment by prasunanand** [comment]
@mohawkjohn  I opened a new PR [#545](https://github.com/SciRuby/nmatrix/pull/545).

Didn't update travis tasks though. Should it be ignored for jruby ?

**Comment by mohawkjohn** [comment]
Transition to #545

**Pull request closed without merging**
