### PR TITLE
Remove ATLAS dependencies from nmatrix gem, add new gems for external library access

### PR DESCRIPTION
**Pull request by wlevine**
nmatrix should now build without any external linear algebra libraries. The ATLAS functionality which was previously part of nmatrix now requires the new nmatrix-atlas gem. The nmatrix-lapacke gem provides a similar ruby interface to nmatrix-atlas, but is designed to work with LAPACK libraries other than ATLAS.

In addition to changes to the structure of the project, I've also made some API changes, which I documented [here](https://github.com/wlevine/nmatrix/wiki/API-Changes).

I've updated the README so hopefully that should give a clear idea of what's going on. I also updated the Ubuntu/Debian section of the [Installation wiki](https://github.com/wlevine/nmatrix/wiki/Installation) (I'll copy this back to the main wiki when everything else gets merged in), but the Mac section still needs work.

One thing I definitely still need to is add license headers to the new files I've added.

### CODE REVIEW

**Comment by mohawkjohn** [comment]
@wlevine I hate to ask this, but can you please rebase into a more limited number of commits? It's tough for people to review your code when it's spaced out like this.

**Comment by wlevine** [comment]
Can't you see all the changes at once by looking at the 'Files changed' tab?

**Comment by mohawkjohn** [comment]
I'm not seeing that — but there are other reasons for doing a rebase. It's generally required for any pull request, because it makes the history much simpler to manage.

**Comment by wlevine** [comment]
Can you just review this: https://github.com/SciRuby/nmatrix/pull/393/files until I get around to rebasing? I still have a few more things to add so I don't want to rebase yet. Also, I disagree that a cleaner history is a more useful history, but it's your project so I'm not going to argue with you about that.

**Comment by mohawkjohn** [comment]
@cjfuller @agarie What do you guys think?

**Comment by wlevine** [comment]
OK, today I added license text to all the new files, cleaned up some comments and a few other bits, and added the last new piece of code I was planning (interfaces for LAPACKE singular value decomposition), so it should be in a better state now. I'll just rebase whenever we're ready to merge, it's not a big deal.

**Comment by wlevine** [comment]
I finally got my hands on a Mac for testing nmatrix. To my surprise the installation was pretty painless, and didn't require anything like rebuilding ruby with gcc like the current instructions suggest. I updated the build instructions here, I hope they work for everyone: https://github.com/wlevine/nmatrix/wiki/Installation

**Comment by mohawkjohn** [comment]
@agarie @cjfuller Would still like your input on whether to waive the rebase requirement.

**Comment by cjfuller** [comment]
I'm ok with not rebasing this.  It's a huge changeset, so I'm not sure it'd be that much more understandable as a single commit anyway...

In general, it might have been nice to rebase into a few conceptually separate commits and do them as separate PRs, but it's probably not worth it at this point...

**Comment by mohawkjohn** [comment]
I was more thinking of rebasing into a couple of conceptually separate commits, but it may be too much of a hairball at this point. Okay, I'll go ahead and merge.

**Comment by wlevine** [comment]
I updated the Installation instructions on the wiki and added a link to the previous version for anyone trying to install 0.1.0: https://github.com/SciRuby/nmatrix/wiki/Installation

**Pull request merged**
