### PR TITLE
Matrix norms implementation

### PR DESCRIPTION
**Pull request by MpoMp**
Progress on #54! Read the issue comments for more info on the progress so far. The numbers in the tests were compared with the results of the same runs in MATLAB.

Looks like the singular values returned by MATLAB's `svd` and  LAPACK's `gesvd` differ after some decimal places. Any feedback on that?

### CODE REVIEW

**Comment by mohawkjohn** [comment]
@abhinavagarwalla Hey, sorry, somehow I missed your comment. Are you still working on this?

**Comment by yoongkang** [comment]
Is it really necessary to compare float64 results to that precision 16th decimal place?

I think we should change the test to compare the difference between the expected result and and the computed result and accept it if it falls below a sensible threshold (say, 1.0e-10) and then call it a day. 

Thoughts? I'd be happy to put that in if that's the only thing holding this up.

**Comment by yoongkang** [comment]
New PR at #400.

**Comment by v0dro** [comment]
Should this be closed? Outdated.

**Pull request closed without merging**
