### PR TITLE
Try to get Travis to work for OSX

### PR DESCRIPTION
**Pull request by yoongkang**
Try to get CI for OSX running (#392).

I'm new to travis. If this fails, please ignore for now.

### CODE REVIEW

**Comment by yoongkang** [comment]
Ah. That didn't run at all. We need to enable this feature by emailing Travis:

See: http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required


> Manual intervention required #

> This feature needs to be enabled manually. If you wish to take advantage of this feature, please send email to support@travis-ci.com, indicating which repository you would like to have it enabled.

**Comment by mohawkjohn** [comment]
I have emailed. Waiting to hear back. Thanks for taking the initiative.

**Comment by mohawkjohn** [comment]
Here's their reply:


I've just enabled multi-os support for https://travis-ci.org/SciRuby/nmatrix
.

You can now trigger builds on Mac OS X, Linux or both at the same time.

Here's what you need to add in your .travis.yml:
http://docs.travis-ci.com/user/multi-os/#Setting-.travis.yml

Is there anything else I can help you with?

**Comment by yoongkang** [comment]
Thanks, tests seem to run for OSX. I'll have to come back to this one after I start knowing what I'm doing.

**Comment by v0dro** [comment]
#430 does this better. Close this?

**Pull request closed without merging**
