### PR TITLE
Issue411 v2

### PR DESCRIPTION
**Pull request by johnmarinelli**
(https://github.com/SciRuby/nmatrix/issues/411)
Hi!  So I've traced the error to the fact that the :float32 and :float64 (likewise for complex) use different epsilons.  I need this epsilon to calculate rank.  I've hardcoded the :float32 epsilon value from my machine right into the function so the tests works, but I actually wanted to pull the value directly from the c code.  Where should I put this?  It would look something like this:

```
#include <float.h>
rb_define_variable("32BIT_EPS", FLT_EPSILON);
rb_define_variable("64BIT_EPS", DBL_EPSILON);
```

Let me know if you have any questions.

### CODE REVIEW

**Comment by mohawkjohn** [comment]
I think it should go in here, maybe? https://github.com/SciRuby/nmatrix/blob/master/ext/nmatrix/ruby_constants.cpp

But it should really be a constant declared on the Float type, not just in the global namespace.

**Comment by johnmarinelli** [comment]
@mohawkjohn how do you suggest I go about doing this?  I'm not very familiar with extending Ruby with C, but I don't imagine it should be very difficult.  should I create a new section in ruby_constants.cpp and just do  rb_define_variable("64BIT_EPS", DBL_EPSILON), build, and 64BIT_EPS will become a value that I can access?

**Comment by mohawkjohn** [comment]
Okay, so Float has an epsilon:

    > Float::EPSILON
    => 2.220446049250313e-16

And you can get it using `rb_const_get`, and that's what you should use for your double epsilon. For your single floating point epsilon, you'll probably want to declare `FLOAT32_EPSILON` on NMatrix. For consistency, let's create an alias from `NMatrix::FLOAT64_EPSILON` to `Float::EPSILON`.

For examples of the former, search the code for `rb_const_get`. For the latter, search the code for `rb_define_const`. That should give you an idea how to accomplish it.

You probably don't actually need to define anything in ruby_constants. I may be wrong about that.

You definitely don't want to name them starting with a number, whatever you do. =)

**Comment by mohawkjohn** [comment]
@johnmarinelli Can you please rebase against master (and squash all your commits into a single one)? Thanks!

**Comment by johnmarinelli** [comment]
see https://github.com/SciRuby/nmatrix/pull/435

**Pull request closed without merging**
