### PR TITLE
Stop using `register` storage class specifier

### PR DESCRIPTION
**Pull request by mrkn**
It was deprecated in C++11.

### CODE REVIEW

**Comment by v0dro** [comment]
looks good.

**Comment by mohawkjohn** [comment]
Do we know why this build isn't passing? I tried restarting a couple of the clang jobs and no luck.

**Comment by mrkn** [comment]
Failed builds seem to be timed out.
2016年7月9日(土) 0:30 Dr. John Woods <notifications@github.com>:

**Comment by mrkn** [comment]
@mohawkjohn Problems were resolved.

**Pull request merged**
