### PR TITLE
solve linear equations expressed in tridiagonal form using two (either/or) functions - .solve_tridiagonal and #solve_tridiagonal

### PR DESCRIPTION
**Pull request by v0dro**
solve linear equations expressed in tridiagonal form
tridiag tests

wip

wip

wip

wip

almost there

docs

docs

tests

### CODE REVIEW

**Comment by mohawkjohn** [comment]
Hey @v0dro, aren't we still waiting on some documentation before merging this? What's the status? Thanks again.

**Comment by v0dro** [comment]
No I've added it already.

You'll find usage examples and references above the class method. Here https://github.com/SciRuby/nmatrix/pull/301/files#diff-ebada9a99c7d63dbc404fc0b986ac7f5R67

**Comment by mohawkjohn** [comment]
Yeah, we talked about this, I think. I want some basic information included
in the rdoc, not just as a link, because links can go away.

**Comment by v0dro** [comment]
Alright.

**Comment by v0dro** [comment]
@mohawkjohn I've updated the docs with relevant info.

**Comment by mohawkjohn** [comment]
Is this dependent on `#solve`? Wondering why it can't automatically merge.

**Comment by mohawkjohn** [comment]
@cjfuller Want to have a look at this one also?

**Comment by v0dro** [comment]
its not.

Thats probably because of `math_spec.rb`

**Comment by cjfuller** [comment]
Again, just a few nits, but looks great, thanks!

**Comment by v0dro** [comment]
@cjfuller check it out now...

**Comment by cjfuller** [comment]
Looks great to me except for the variable names John pointed out.  Thanks!

**Comment by v0dro** [comment]
done

**Comment by mohawkjohn** [comment]
@v0dro Sorry, would you mind rebasing this against master so we can merge automatically? I *still* don't have a working install on my laptop.

**Comment by v0dro** [comment]
Could you please tell me the most error-proof way to do that?

Last time I tried cherry picking those commits after merging with master, but it would not let me do that due to some conflicts. I end up copy pasting the code into a new branch that was derived from master, which caused a lot of confusion and errors.

**Comment by mohawkjohn** [comment]
That's a good question. Here's what I found when I searched: http://www.daigo.org/2014/05/conflict-resolution-on-git/

**Comment by v0dro** [comment]
Thank you John that was super helpful.

**Pull request closed without merging**
