### PR TITLE
Random orthogonal NMatrix

### PR DESCRIPTION
**Pull request by agisga**
I have written a shortcut NMatrix.randomortho (or NMatrix.randortho) to randomly generate an *orthogonal* NMatrix. More precisely, the algorithm creates a Householder matrix from random numbers, which is similar to Stewart 1980, "The Efficient Generation of Random Orthogonal Matrices  with an Application to Condition Estimators", though much simplified.
Random orthogonal matrix generation is often required in Monte Carlo simulations, and I believe in some optimization algorithms. It can also be useful for prototyping and checking other computational methods.

### CODE REVIEW

**Comment by agisga** [comment]
I realized that the method does not work for integer data types. But that's an easy fix, because all orthogonal matrices with integer entries can be obtained as column permutations of the diagonal matrix D, where D only has +1 or -1 entries on the diagonal. I am fixing it in my code.
(Sorry if my contribution seems awkward in any way. I am new to Ruby and github.)

**Comment by mohawkjohn** [comment]
Hi, thanks for the patch! I'd appreciate it if you could do two things for me before I look at this. Firstly, can you add an underscore to the method name (`random_ortho` and `rand_ortho`)? Secondly, can you please rebase your commits into a single one? This makes it much easier for us to look at your code and ultimately merge it.

**Comment by mohawkjohn** [comment]
You don't actually have to close to rebase. You just rebase on your own machine, then do `git push -f origin whichever_branch`, and it'll replace the commits in this pull request automatically.

**Comment by agisga** [comment]
Thanks for for the advice. Since I have no idea about the git workflow, I made the mistake of working on my master branch only and my pull request was from master. So, I will start over because I want to work on multiple separate patches.

**Comment by mohawkjohn** [comment]
Oh, okay. No worries, then. =) We've all made that mistake in the past.

**Pull request closed without merging**
