### PR TITLE
Avoid unnecessary heap allocation of SLICE objects

### LINKED ISSUE #541: NMatrix getter and setter way slower than Matrix
I'm using NMatrix for [competitive programming](https://en.wikipedia.org/wiki/Competitive_programming) for a while now and I have found NMatrix to be **slower** than Matrix for most of my programs. For example methods such as `[]`, `[]=` which are frequently used in my programs are slower in NMatrix.

[Here](https://gist.github.com/lokeshh/cc7b428fda100dedb005067c01b355db)'s a benchmark I ran and following are the results:

```ruby
       user     system      total        real
Matrix getter  3.700000   0.020000   3.720000 (  3.744560)
NMatrix getter 12.930000   0.060000  12.990000 ( 13.065677)
Matrix setter  2.920000   0.020000   2.940000 (  2.965361)
NMatrix setter 16.600000   0.060000  16.660000 ( 16.889194)
```

### PR DESCRIPTION
**Pull request by wlevine**
This partly fixes #541. Here are the results of Lokesh's benchmark with the patch:
```
       user     system      total        real
Matrix getter  1.960000   0.000000   1.960000 (  1.961916)
NMatrix getter  1.570000   0.000000   1.570000 (  1.583510)
Matrix setter  1.680000   0.000000   1.680000 (  1.688569)
NMatrix setter  3.070000   0.000000   3.070000 (  3.077533)
```

`#[]` is probably fast enough now. `#[]=` is a lot faster than before, but may still need more work.

@mohawkjohn I think this is the right way to do this, but I'd appreciate it if you take a look.

### CODE REVIEW

**Comment by v0dro** [comment]
Why are the tests failing?

**Comment by mohawkjohn** [comment]
@v0dro Looks like the failures relate to #522 and #538, or at least resemble those. I can't see how any of @wlevine's changes would have caused this, though — can you?

**Comment by v0dro** [comment]
@mohawkjohn I think you're right. Those other bugs will need fixing for the build to pass.

**Comment by wlevine** [comment]
@mohawkjohn Done!

**Pull request merged**
