### PR TITLE
Change tabs to 2 spaces

### LINKED ISSUE #417: Fix all indenting — two spaces, not one tab
What the heck happened to the indenting? No tabs should be used anywhere in the code. It should always be two spaces.

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes #417

### CODE REVIEW

**Comment by mohawkjohn** [comment]
I don't think that addresses all the locations. For example, I noticed a lot of tabs in ruby_constants.h and ruby_constants.cpp.

**Comment by lokeshh** [comment]
Okay, I will fix it.

**Comment by lokeshh** [comment]
How about now?

**Comment by mohawkjohn** [comment]
Yes. Great. Now if you can just rebase the two into one commit, that would be excellent, and I can merge. Thanks for your contribution! =)

**Comment by lokeshh** [comment]
Done. I will look forward to contribute more.

**Pull request merged**
