### PR TITLE
Temporary fix for matrix decomposition

### PR DESCRIPTION
**Pull request by AdiChat**
#436 This is a temporary fix for the matrix inverse bug. I will be analysing the implementation of standard algorithms closely to find the exact point from where this issue is arising. Then I submit a patch for eliminating the bug. Till then this fix is satisfactory.

@AdiChat

### CODE REVIEW

**Comment by AdiChat** [comment]
It seems I need to review the checks.

**Comment by mohawkjohn** [comment]
What issue is this supposed to address? (As in, what's the number?)

**Comment by shahsaurabh0605** [comment]
Actually this addresses [#436](https://github.com/SciRuby/nmatrix/issues/436) which I opened. I already sent a PR which tries to solve the issue but it uses some of the local variables. This temporary fix will also not solve the issue as the value of A_elements is anyways changing.

**Comment by AdiChat** [comment]
@shahsaurabh0605 I can achieve the same without altering the value of A_ elements by a minor change in implementation. According to you, how would this solve the issue? 
@mohawkjohn I have analysed the algorithms employed and it seems to be an implementation issue around matrix decomposition.

**Pull request closed without merging**
