### PR TITLE
NMatrix FFTW plugin

### LINKED ISSUE #397: Add Magdalen's FFTW as an NMatrix extension
@thisMagpie's last year's GSOC project (https://github.com/thisMagpie/fftw) has not seen active use yet.

Maybe adding this to nmatrix like ATLAS and LAPACKE would be great. I think most of the work regarding interfacing nmatrix with FFTW is almost done (though I do have some opinions about the way the nmatrix C API has been used).

WE can then release this as nmatrix-fftw.

### PR DESCRIPTION
**Pull request by v0dro**
Hello,

I'm working on the nmatrix FFTW plugin (resolves #397). I'm currently almost done with FFTW's complex input/complex output interface.

The top level Ruby interface looks something like this:

``` ruby

input = NMatrix.new(
  [10],
  # Initialize nmatrix elements.,
  dtype: :complex128
 )

# This tells FFTW to create a 'plan' so that it can most efficiently calculate FFTs for the given
# memory locations and number of elements. 
# This class also allocates memory for the plan and prepares the relevant data arrays as are
# required by FFTW.
#The shape of the plan is 10 in this case and has a single dimension. The `c2c` indicates 
# that this is a complex input/complex output type DFT# See the file fftw_spec.rb for more 
# examples of plans.
plan = NMatrix::FFTW::Plan.new([10], flags: :estimate, dim: 1, type: :c2c)

# The `set_input` function receives the input as an NMatrix and copies this input to the 
# memory that has been set aside for FFTW.
plan.set_input(input) 

# This function executes the plan and stores the output in the relevant FFTW data structures.
plan.execute

# This function retrieves the output and copies it to an NMatrix object, that is returned to the user.
output = plan.output
```

For more examples, see [fftw_spec.rb](https://github.com/v0dro/nmatrix/blob/nmatrix-fftw/spec/plugins/fftw/fftw_spec.rb).

### CODE REVIEW

**Comment by v0dro** [comment]
Feedback on the code/interface will be appreciated.

I will be done with the plugin (i.e. implementing real input/complex output and complex input/real output FFTs) in a few days. I will also implement a top level novice interface later which will reduce computation of FFTs to a single line of Ruby, but will not permit the same level of control that this interface provides.

Please don't merge this PR until then.

**Comment by mohawkjohn** [comment]
My first piece of feedback is I don't like the c2c, r2c, etc. abbreviations. This is Ruby. Let's do `from: :complex, to: :complex`. Or if you really want to abbreviate it, just do `type: :complex_complex`.

**Comment by v0dro** [comment]
Yeah `complex_complex` would be better.

**Comment by v0dro** [comment]
@mohawkjohn I'm done with the API for NMatrix::FFTW. Now I will implement easier to use accessor functions, intuitive DSLs and write documentation.

In the meanwhile could you please review the API? You can see all my tests [in this file](https://github.com/v0dro/nmatrix/blob/nmatrix-fftw/spec/plugins/fftw/fftw_spec.rb). Any feedback would be greatly appreciated.

**Comment by v0dro** [comment]
@mohawkjohn @agarie  I'm pretty much done with this feature including documentation. Only the FFTW DSL remains which I'll finish off tonight.

Please review and let me know your thoughts ASAP so that I can submit my completion report to the team at the Ruby Association.

**Comment by v0dro** [comment]
@mohawkjohn @agarie I am done with this feature.

Request and merge ASAP because I need to submit reports to the Ruby Association Grant committee.

**Comment by v0dro** [comment]
Can someone please review these changes?

**Comment by v0dro** [comment]
So I tried a lot to make travis work in this case, but it wouldn't happen with FFTW because the library `libfftw3-bin` is not present in the ubuntu 12.04 sources, and upgrading the dist to 14.04 on travis led to failure of other libraries.

**Comment by wlevine** [comment]
Do you have the logs from when you tried using 14.04? We should be able to fix that, right?

**Comment by v0dro** [comment]
So it fails [very weirdly for FFTW](https://travis-ci.org/SciRuby/nmatrix/jobs/100668518#L5564) (I don't get that bug on my PC and the values passed to the function in question seem fine too).

For ATLAS, it's failing [this way](https://travis-ci.org/SciRuby/nmatrix/jobs/100668514#L3111). I think it's something about the wrong ATLAS getting installed.

**Comment by mohawkjohn** [comment]
Okay, seems like most of the comments I had have been resolved in later commits.

@cjfuller You have time to look over this stuff, too?

@v0dro Are you ready to have it merged?

**Comment by v0dro** [comment]
@mohawkjohn  I'd prefer first merging @mrkn 's changes relating to Travis and RARRAY_AREF into my branch before having this merged. I think it will conflict since I've made changes to those files too.

**Comment by mohawkjohn** [comment]
Okay, I merged the other request.

**Comment by v0dro** [comment]
@mohawkjohn all your suggested changes have been implemented. Merging.

**Pull request merged**
